unknown-platform-enabled: true
android-enabled: true
ios-enabled: true
macos-enabled: true
gearvr-enabled: true
windows10-enabled: true
windowsedu-enabled: true
ps4-enabled: true
switch-enabled: true
xboxone-enabled: true
windowsphone-enabled: true