name: GeyserBlockPlatform
description: "${description}"
version: "${version}"
authors: [Camotoy, Konicai, Jens]

main: dev.kejona.geyserblockplatform.spigot.GeyserBlockPlatformSpigot
api-version: 1.13
softdepend: [floodgate, Geyser-Spigot]

permissions:
  geyserblockplatform.bypass:
    description: Give player a bypass for platform checker
    default: op