name: GeyserBlockPlatform
description: ${description}

version: ${version}
main: com.github.camotoy.geyserblockplatform.spigot.GeyserBlockPlatformSpigot
api-version: 1.13
softdepend: [floodgate]

permissions:
  geyserblockplatform.bypass:
    description: Give player a bypass for platform checker
    default: op