
# Kick message when the bedrock platform is not allowed
platform-message: "Invalid bedrock platform:ยง4 %s"
# Kick message when the input mode is not allowed
input-message: "Invalid input mode:ยง4 %s"
# Kick message when the UI profile is not allowed
profile-message: "Invalid UI profile:ยง4 %s"

# See https://github.com/GeyserMC/api/blob/master/base/src/main/java/org/geysermc/api/util/BedrockPlatform.java#L31-L45
# for more descriptive names
platforms:
  UNKNOWN: true
  GOOGLE: true
  IOS: true
  OSX: true
  AMAZON: true
  GEARVR: true
  HOLOLENS: true
  UWP: true
  WIN32: true
  DEDICATED: true
  TVOS: true
  PS4: true
  NX: true
  XBOX: true
  WINDOWS_PHONE: true

# Input mode
inputs:
  UNKNOWN: true
  KEYBOARD_MOUSE: true
  TOUCH: true
  CONTROLLER: true
  VR: true

# UI profile
profiles:
  CLASSIC: true
  POCKET: true
