# Disable or enable platforms.
unknown-platform-enabled: true
android-enabled: true
ios-enabled: true
macos-enabled: true
gearvr-enabled: true
windows10-enabled: true
windowsedu-enabled: true
ps4-enabled: true
switch-enabled: true
xboxone-enabled: true
windowsphone-enabled: true

# Disconnect message to players.
no-access-message: "&6Sorry your platform does not have access to this server!"

# Proxy options to exclude specified server.
# The "all" option will deny access to the whole network.
deny-server-access:
#  - "all"
  - "serverhere"

