
name: build
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: gradle/wrapper-validation-action@v1
      
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - uses: gradle/gradle-build-action@2
        with:
          arguments: clean build
          gradle-home-cache-cleanup: true
          
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: CrossplatForms
          path: |
            spigot/build/libs/GeyserBlockPlatform-Spigot.jar
            bungeecord/build/libs/GeyserBlockPlatform-Bungeecord.jar
            velocity/build/libs/GeyserBlockPlatform-Velocity.jar
